/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hms.form;


import com.hms.query.Query;

import javax.swing.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;

/**
 * @author Mahadi Indra <indra-182 on github.com>
 */
public class CheckIn extends javax.swing.JFrame {

    /**
     * Creates new form CheckIn
     */

    public CheckIn() {
        initComponents();
        txtSetTanggalCheckIn.setEditable(false);
        txtSetHarga.setEditable(false);
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        Calendar calendar = Calendar.getInstance();
        txtSetTanggalCheckIn.setText(dateFormat.format(calendar.getTime()));
        setDataRooms();
    }

    String bed;
    String roomType;
    String roomNumber;
    String price;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtSetNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSetEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtSetTelepon = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dropdownJenisKelamin = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtSetId = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSetAlamat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSetTanggalCheckIn = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        dropdownSetTipeKamar = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        dropdownSetTipeKasur = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtSetHarga = new javax.swing.JTextField();
        btnBookRoom = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        dropdownSetNomorKamar = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txtSetNegara = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(50, 118));
        setUndecorated(true);

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel2.setText("Nama");

        txtSetNama.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel3.setText("Email");

        txtSetEmail.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        txtSetEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSetEmailActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel1.setText("No. Telepon");

        txtSetTelepon.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel4.setText("Jenis Kelamin");

        dropdownJenisKelamin.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        dropdownJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Pilih", "Laki-Laki", "Perempuan"}));

        jLabel5.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel5.setText("ID");

        txtSetId.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel6.setText("Alamat");

        txtSetAlamat.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel7.setText("Tanggal Check In");

        txtSetTanggalCheckIn.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel8.setText("Tipe Kamar");

        dropdownSetTipeKamar.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        dropdownSetTipeKamar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Pilih", "Standar", "Superior", "Deluxe"}));
        dropdownSetTipeKamar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dropdownSetTipeKamarItemStateChanged(evt);
            }
        });
        dropdownSetTipeKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropdownSetTipeKamarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel9.setText("Tipe Kasur");

        jLabel10.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel10.setText("Nomor Kamar");

        dropdownSetTipeKasur.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        dropdownSetTipeKasur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Pilih", "Single Bed", "Twin Bed", "Double Bed"}));
        dropdownSetTipeKasur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropdownSetTipeKasurActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel11.setText("Harga");

        txtSetHarga.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N

        btnBookRoom.setText("Book Room");
        btnBookRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookRoomActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        dropdownSetNomorKamar.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        dropdownSetNomorKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropdownSetNomorKamarActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel12.setText("Negara");

        txtSetNegara.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(193, 193, 193)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtSetNama)
                                        .addComponent(txtSetEmail)
                                        .addComponent(txtSetTelepon)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel2))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(dropdownJenisKelamin, 0, 284, Short.MAX_VALUE))
                                .addGap(258, 258, 258)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)
                                        .addComponent(txtSetAlamat)
                                        .addComponent(jLabel7)
                                        .addComponent(txtSetTanggalCheckIn)
                                        .addComponent(txtSetId, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                        .addComponent(jLabel12)
                                        .addComponent(txtSetNegara))
                                .addGap(167, 167, 167)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnBookRoom)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnClear))
                                        .addComponent(dropdownSetNomorKamar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(dropdownSetTipeKasur, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel9)
                                                        .addComponent(jLabel10)
                                                        .addComponent(jLabel11)
                                                        .addComponent(jLabel8)
                                                        .addComponent(txtSetHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(dropdownSetTipeKamar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(342, 342, 342))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(180, 180, 180)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtSetNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(26, 26, 26)
                                                .addComponent(jLabel3)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtSetEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel1)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtSetTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel4)
                                                .addGap(18, 18, 18)
                                                .addComponent(dropdownJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel8)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(dropdownSetTipeKamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(26, 26, 26)
                                                                .addComponent(jLabel9)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(dropdownSetTipeKasur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel10))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel5)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(txtSetId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(26, 26, 26)
                                                                .addComponent(jLabel6)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(txtSetAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel12)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(22, 22, 22)
                                                                                .addComponent(dropdownSetNomorKamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(txtSetNegara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel11)
                                                        .addComponent(jLabel7))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(txtSetHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtSetTanggalCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnBookRoom)
                                        .addComponent(btnClear))
                                .addContainerGap(516, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSetEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSetEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSetEmailActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new CheckIn().setVisible(true);
    }//GEN-LAST:event_btnClearActionPerformed

    private void dropdownSetTipeKasurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdownSetTipeKasurActionPerformed
        // TODO add your handling code here:
        setDataRooms();
    }//GEN-LAST:event_dropdownSetTipeKasurActionPerformed

    private void dropdownSetNomorKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdownSetNomorKamarActionPerformed
        // TODO add your handling code here:
        roomNumber = (String) dropdownSetNomorKamar.getSelectedItem();
        try {
            ResultSet rs = Query.getData("select * from rooms where room_number = '" + roomNumber + "'");
            while (rs.next()) {
                txtSetHarga.setText(rs.getString(4));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_dropdownSetNomorKamarActionPerformed

    private void dropdownSetTipeKamarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dropdownSetTipeKamarItemStateChanged
        // TODO add your handling code here:
        setDataRooms();
    }//GEN-LAST:event_dropdownSetTipeKamarItemStateChanged

    private void btnBookRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookRoomActionPerformed
        // TODO add your handling code here:
        int id = 1;
        String name = txtSetNama.getText();
        String email = txtSetEmail.getText();
        String phoneNumber = txtSetTelepon.getText();
        String gender = (String) dropdownJenisKelamin.getSelectedItem();
        String idCard = txtSetId.getText();
        String nationality = txtSetNegara.getText();
        String address = txtSetAlamat.getText();
        String checkInDate = txtSetTanggalCheckIn.getText();
        String roomType = (String) dropdownSetTipeKamar.getSelectedItem();
        String bedType = (String) dropdownSetTipeKasur.getSelectedItem();
        String roomNumber = (String) dropdownSetNomorKamar.getSelectedItem();
        String price = txtSetHarga.getText();

        try {
            String query = "SELECT MAX(id) FROM transactions";
            ResultSet rs = Query.getData(query);
            while (rs.next()) {
                id = rs.getInt(1) + 1;
                if (!price.equals("")) {
                    String queryUpdateStatusRoom = "UPDATE rooms SET status = 'Booked' WHERE room_number = '" + roomNumber + "'";
                    Query.setData(queryUpdateStatusRoom, "");
                    String queryInsertData = "INSERT INTO transactions(id, name, email, phone_number, gender, id_card, nationality, address, check_in_date, room_type, bed, room_number, price) "
                            + "VALUES ('" + id + "', '" + name + "', '" + email + "', '" + phoneNumber + "', '" + gender + "', '" + idCard + "', '" + nationality + "', '" + address + "', '" + checkInDate + "', '" + roomType + "', '" + bedType + "', '" + roomNumber + "', '" + price + "')";
                    Query.setData(queryInsertData, "Kamar telah dipesan");
                    setVisible(false);
                    new CheckIn().setVisible(true);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_btnBookRoomActionPerformed

    private void dropdownSetTipeKamarActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }


    public void setDataRooms() {
        dropdownSetNomorKamar.removeAllItems();
        txtSetHarga.setText("");
        bed = (String) dropdownSetTipeKasur.getSelectedItem();
        roomType = (String) dropdownSetTipeKamar.getSelectedItem();

        try {
            ResultSet rs = Query.getData("select * from rooms where room_type = '" + roomType + "' and bed = '" + bed + "' and status = 'Available'");
            while (rs.next()) {
                String roomNumber = rs.getString(1);
                dropdownSetNomorKamar.addItem(roomNumber);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBookRoom;
    private javax.swing.JButton btnClear;
    private javax.swing.JComboBox<String> dropdownJenisKelamin;
    private javax.swing.JComboBox<String> dropdownSetNomorKamar;
    private javax.swing.JComboBox<String> dropdownSetTipeKamar;
    private javax.swing.JComboBox<String> dropdownSetTipeKasur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtSetAlamat;
    private javax.swing.JTextField txtSetEmail;
    private javax.swing.JTextField txtSetHarga;
    private javax.swing.JTextField txtSetId;
    private javax.swing.JTextField txtSetNama;
    private javax.swing.JTextField txtSetNegara;
    private javax.swing.JTextField txtSetTanggalCheckIn;
    private javax.swing.JTextField txtSetTelepon;
    // End of variables declaration//GEN-END:variables
}
