/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hms.form;

import com.hms.query.Query;

import javax.swing.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;

/**
 * @author Mahadi Indra <indra-182 on github.com>
 */
public class CheckIn extends javax.swing.JFrame {

    /**
     * Creates new form CheckIn
     */
    public CheckIn() {
        initComponents();
        txtSetTanggalCheckIn.setEditable(false);
        txtSetHarga.setEditable(false);
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        Calendar calendar = Calendar.getInstance();
        txtSetTanggalCheckIn.setText(dateFormat.format(calendar.getTime()));
        setNumberRooms();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtSetNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSetEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtSetTelepon = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dropdownJenisKelamin = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtSetId = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSetNegara = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSetTanggalCheckIn = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        dropdownSetTipeKamar = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        dropdownSetTipeKasur = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtSetHarga = new javax.swing.JTextField();
        btnBookRoom = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        dropdownSetNomorKamar = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txtSetAlamat = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel2.setText("Nama");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 180, -1, -1));

        txtSetNama.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        getContentPane().add(txtSetNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 216, 294, -1));

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel3.setText("Email");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 266, -1, -1));

        txtSetEmail.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        getContentPane().add(txtSetEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 302, 294, -1));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel1.setText("No. Telepon");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 344, -1, -1));

        txtSetTelepon.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        getContentPane().add(txtSetTelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 380, 294, -1));

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel4.setText("Jenis Kelamin");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 422, -1, -1));

        dropdownJenisKelamin.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        dropdownJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Laki-Laki", "Perempuan" }));
        getContentPane().add(dropdownJenisKelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 458, 294, -1));

        jLabel5.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel5.setText("ID");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(733, 180, -1, -1));

        txtSetId.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        getContentPane().add(txtSetId, new org.netbeans.lib.awtextra.AbsoluteConstraints(733, 216, 350, -1));

        jLabel6.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel6.setText("Alamat");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(733, 344, -1, -1));

        txtSetNegara.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        getContentPane().add(txtSetNegara, new org.netbeans.lib.awtextra.AbsoluteConstraints(733, 302, 350, -1));

        jLabel7.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel7.setText("Tanggal Check In");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(733, 431, -1, -1));

        txtSetTanggalCheckIn.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        getContentPane().add(txtSetTanggalCheckIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(733, 467, 350, -1));

        jLabel8.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel8.setText("Tipe Kamar");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 180, -1, -1));

        dropdownSetTipeKamar.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        dropdownSetTipeKamar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Standar", "Superior", "Deluxe" }));
        getContentPane().add(dropdownSetTipeKamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 216, 355, -1));

        jLabel9.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel9.setText("Tipe Kasur");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 266, -1, -1));

        jLabel10.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel10.setText("Nomor Kamar");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 344, -1, -1));

        dropdownSetTipeKasur.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        dropdownSetTipeKasur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Single Bed", "Twin Bed", "Double Bed" }));
        dropdownSetTipeKasur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropdownSetTipeKasurActionPerformed(evt);
            }
        });
        getContentPane().add(dropdownSetTipeKasur, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 302, 355, -1));

        jLabel11.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel11.setText("Harga");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 431, -1, -1));

        txtSetHarga.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        getContentPane().add(txtSetHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 467, 355, -1));

        btnBookRoom.setText("Booking Kamar");
        btnBookRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookRoomActionPerformed(evt);
            }
        });
        getContentPane().add(btnBookRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 546, -1, -1));

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1548, 546, -1, -1));

        dropdownSetNomorKamar.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        getContentPane().add(dropdownSetNomorKamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 384, 355, -1));

        jLabel12.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel12.setText("Negara");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(733, 266, -1, -1));

        txtSetAlamat.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        getContentPane().add(txtSetAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(733, 384, 350, -1));

        btnBack.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hms/images/logout.jpg"))); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hms/images/mainbg.jpg"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new CheckIn().setVisible(true);
    }//GEN-LAST:event_btnClearActionPerformed

    private void dropdownSetTipeKasurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdownSetTipeKasurActionPerformed
        // TODO add your handling code here:
        setNumberRooms();
    }//GEN-LAST:event_dropdownSetTipeKasurActionPerformed

    private void btnBookRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookRoomActionPerformed
        // TODO add your handling code here:
        int id = 0;
        String name = txtSetNama.getText();
        String email = txtSetEmail.getText();
        String phoneNumber = txtSetTelepon.getText();
        String gender = (String) dropdownJenisKelamin.getSelectedItem();
        String idCard = txtSetId.getText();
        String nationality = txtSetNegara.getText();
        String address = txtSetAlamat.getText();
        String checkInDate = txtSetTanggalCheckIn.getText();
        String roomType = (String) dropdownSetTipeKamar.getSelectedItem();
        String bedType = (String) dropdownSetTipeKasur.getSelectedItem();
        String roomNumber = (String) dropdownSetNomorKamar.getSelectedItem();
        String price = txtSetHarga.getText();

        try {
            String query = "SELECT MAX(id) FROM transactions";
            ResultSet rs = Query.getData(query);
            while (rs.next()) {
                id = rs.getInt(1) + 1;
                if (!price.isEmpty()) {
                    String queryUpdateStatusRoom = "UPDATE rooms SET status = 'Booked' WHERE room_number = '" + roomNumber + "'";
                    Query.setData(queryUpdateStatusRoom, "");
                    String queryInsertData = "INSERT INTO transactions(id, name, email, phone_number, gender, id_card, nationality, address, check_in_date, room_type, bed, room_number, price) "
                            + "VALUES ('" + id + "', '" + name + "', '" + email + "', '" + phoneNumber + "', '" + gender + "', '" + idCard + "', '" + nationality + "', '" + address + "', '" + checkInDate + "', '" + roomType + "', '" + bedType + "', '" + roomNumber + "', '" + price + "')";
                    Query.setData(queryInsertData, "Kamar telah dipesan");
                    setVisible(false);
                    new CheckIn().setVisible(true);
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_btnBookRoomActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new AdminHome().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void setNumberRooms() {
        dropdownSetNomorKamar.removeAllItems();
        txtSetHarga.setText("");
        String bed;
        String roomType;
        bed = (String) dropdownSetTipeKasur.getSelectedItem();
        roomType = (String) dropdownSetTipeKamar.getSelectedItem();

        try {
            ResultSet rs = Query.getData("select * from rooms where room_type = '" + roomType + "' and bed = '" + bed + "' and status = 'Available'");
            while (rs.next()) {
                String roomNumber = rs.getString("room_number");
                dropdownSetNomorKamar.addItem(roomNumber);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBookRoom;
    private javax.swing.JButton btnClear;
    private javax.swing.JComboBox<String> dropdownJenisKelamin;
    private javax.swing.JComboBox<String> dropdownSetNomorKamar;
    private javax.swing.JComboBox<String> dropdownSetTipeKamar;
    private javax.swing.JComboBox<String> dropdownSetTipeKasur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtSetAlamat;
    private javax.swing.JTextField txtSetEmail;
    private javax.swing.JTextField txtSetHarga;
    private javax.swing.JTextField txtSetId;
    private javax.swing.JTextField txtSetNama;
    private javax.swing.JTextField txtSetNegara;
    private javax.swing.JTextField txtSetTanggalCheckIn;
    private javax.swing.JTextField txtSetTelepon;
    // End of variables declaration//GEN-END:variables
}
