/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hms.form;

import com.hms.model.Users;
import com.hms.query.Query;

import javax.swing.*;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 * @author Mahadi Indra <indra-182 on github.com>
 */
public class ForgotPassword extends javax.swing.JFrame {

    /**
     * Creates new form ForgotPassword
     */
    public ForgotPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        txtEmail = new javax.swing.JLabel();
        txtSecurityQuestion = new javax.swing.JLabel();
        txtAnswer = new javax.swing.JLabel();
        txtPassword = new javax.swing.JLabel();
        txtPasswordAgain = new javax.swing.JLabel();
        txtSetEmail = new javax.swing.JTextField();
        txtSetSecurityQuestion = new javax.swing.JTextField();
        txtSetAnswer = new javax.swing.JTextField();
        txtSetPassword = new javax.swing.JPasswordField();
        txtSetPasswordAgain = new javax.swing.JPasswordField();
        btnCari = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lupa Password");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 300, -1, -1));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hms/images/close.jpg"))); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1840, 10, 50, 50));

        txtEmail.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setText("Email");
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, -1, -1));

        txtSecurityQuestion.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        txtSecurityQuestion.setForeground(new java.awt.Color(255, 255, 255));
        txtSecurityQuestion.setText("Pertanyaan Keamanan");
        getContentPane().add(txtSecurityQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, -1, -1));

        txtAnswer.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        txtAnswer.setForeground(new java.awt.Color(255, 255, 255));
        txtAnswer.setText("Jawaban");
        getContentPane().add(txtAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 510, -1, -1));

        txtPassword.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setText("Masukkan Password Baru");
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 570, -1, -1));

        txtPasswordAgain.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        txtPasswordAgain.setForeground(new java.awt.Color(255, 255, 255));
        txtPasswordAgain.setText("Masukkan Password Baru Lagi");
        getContentPane().add(txtPasswordAgain, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 640, -1, -1));

        txtSetEmail.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        getContentPane().add(txtSetEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 390, 378, -1));

        txtSetSecurityQuestion.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        getContentPane().add(txtSetSecurityQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 450, 378, -1));

        txtSetAnswer.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        getContentPane().add(txtSetAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 510, 378, -1));

        txtSetPassword.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        getContentPane().add(txtSetPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 570, 378, -1));

        txtSetPasswordAgain.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        getContentPane().add(txtSetPasswordAgain, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 640, 378, -1));

        btnCari.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        getContentPane().add(btnCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 390, -1, -1));

        btnSave.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 720, -1, -1));

        btnLogin.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 720, -1, -1));

        btnRegister.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 720, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hms/images/lupapassword.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        int choose = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin keluar?", "Exit", JOptionPane.YES_NO_OPTION);
        if (choose == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        Users users = new Users();
        users.setEmail(txtSetEmail.getText());
        users.setSecurityQuestion(txtSetSecurityQuestion.getText());
        users.setAnswer(txtSetAnswer.getText());
        users.setPassword(String.valueOf(txtSetPassword.getPassword()));

        if (users.getEmail().isEmpty() || users.getSecurityQuestion().isEmpty() || users.getAnswer().isEmpty() || users.getPassword().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Semua kolom harus diisi");
            return;
        }

        if (!users.getPassword().equals(String.valueOf(txtSetPasswordAgain.getPassword()))) {
            JOptionPane.showMessageDialog(null, "Password tidak sama");
            return;
        }

        if (!validateAllData(users)) {
            JOptionPane.showMessageDialog(null, "Jawaban Anda salah");
            return;
        }

        if (validateAllData(users) && users.getPassword().equals(String.valueOf(txtSetPasswordAgain.getPassword()))) {
            String query = "UPDATE users SET password = '" + users.getPassword() + "' WHERE email = '" + users.getEmail() + "'";
            Query.setData(query, "Sukses Memperbarui Password");
            setVisible(false);
            new ForgotPassword().setVisible(true);
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        Users users = new Users();
        users.setEmail(txtSetEmail.getText());

        if (users.getEmail().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Email harus diisi");
            return;
        }

        if (!Register.validateEmail(users.getEmail())) {
            JOptionPane.showMessageDialog(null, "Email tidak ditemukan");
            return;
        }

        if (Register.validateEmail(users.getEmail())) {
            JOptionPane.showMessageDialog(null, "Email ditemukan");
            txtSetSecurityQuestion.setText(getSecurityQuestion(users.getEmail()));
            txtSetEmail.setEditable(false);
            txtSetSecurityQuestion.setEditable(false);
            return;
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Register().setVisible(true);
    }//GEN-LAST:event_btnRegisterActionPerformed

    private static String getSecurityQuestion(String email) {
        String securityQuestion = "";
        String query = "SELECT security_question FROM users WHERE email = '" + email + "'";
        ResultSet resultSet = Query.getData(query);
        try {
            if (resultSet.next()) {
                securityQuestion = resultSet.getString("security_question");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return securityQuestion;
    }

    private static boolean validateAllData(Users users) {
        String query = "SELECT * FROM users WHERE email = '" + users.getEmail() + "' AND security_question = '" + users.getSecurityQuestion() + "' AND answer = '" + users.getAnswer() + "'";
        ResultSet resultSet = Query.getData(query);
        try {
            if (resultSet.next()) {
                return true;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return false;
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel txtAnswer;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JLabel txtPassword;
    private javax.swing.JLabel txtPasswordAgain;
    private javax.swing.JLabel txtSecurityQuestion;
    private javax.swing.JTextField txtSetAnswer;
    private javax.swing.JTextField txtSetEmail;
    private javax.swing.JPasswordField txtSetPassword;
    private javax.swing.JPasswordField txtSetPasswordAgain;
    private javax.swing.JTextField txtSetSecurityQuestion;
    // End of variables declaration//GEN-END:variables
}
