/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hms.form;

import com.hms.model.Users;
import com.hms.query.Query;

import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 * @author Mahadi Indra <indra-182 on github.com>
 */
public class Login extends javax.swing.JFrame {


    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JLabel();
        txtPassword = new javax.swing.JLabel();
        txtSetEmail = new javax.swing.JTextField();
        txtSetPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        btnLupaPassword = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Login");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 340, -1, -1));

        txtEmail.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setText("Email");
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, -1, -1));

        txtPassword.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setText("Password");
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 530, -1, -1));

        txtSetEmail.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        txtSetEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSetEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtSetEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 440, 600, -1));

        txtSetPassword.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        getContentPane().add(txtSetPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 530, 600, -1));

        btnLogin.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 640, -1, -1));

        btnRegister.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 640, -1, -1));

        btnLupaPassword.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btnLupaPassword.setText("Lupa Password?");
        btnLupaPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLupaPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(btnLupaPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 640, -1, -1));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hms/images/close.jpg"))); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1860, 10, 50, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hms/images/login.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        Users users = new Users();
        users.setEmail(txtSetEmail.getText());
        String encryptedPassword = Register.encryptPass(String.valueOf(txtSetPassword.getPassword()));
        users.setPassword(encryptedPassword);

        if (users.getEmail().isEmpty() || users.getPassword().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Email dan Password harus diisi");
            return;
        }

        if (!Register.validateEmail(users.getEmail())) {
            JOptionPane.showMessageDialog(null, "Email tidak ditemukan");
            return;
        }

        if (!validateLogin(users.getEmail(), users.getPassword())) {
            JOptionPane.showMessageDialog(null, "Email atau Password salah");
            return;
        }

        if (validateLogin(users.getEmail(), users.getPassword())) {
            if (users.getEmail().equals("superadmin@mailinator.com")) {
                setVisible(false);
                new SuperAdminHome().setVisible(true);
            } else {
                ResultSet resultSet = Query.getData("SELECT * FROM users WHERE email = '" + users.getEmail() + "' AND password = '" + users.getPassword() + "'");
                try {
                    if (resultSet.next()) {
                        if (resultSet.getString("status").equals("Active")) {
                            setVisible(false);
                            new AdminHome().setVisible(true);
                        } else {
                            JOptionPane.showMessageDialog(null, "Akun anda belum aktif, silakan hubungi Super Admin");
                        }
                    }
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Register().setVisible(true);
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        int choose = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin keluar?", "Exit", JOptionPane.YES_NO_OPTION);
        if (choose == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnCloseActionPerformed

    private void txtSetEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSetEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSetEmailActionPerformed

    private void btnLupaPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLupaPasswordActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new ForgotPassword().setVisible(true);
    }//GEN-LAST:event_btnLupaPasswordActionPerformed

    private boolean validateLogin(String email, String password) {
        String query = "SELECT * FROM users WHERE email = '" + email + "' AND password = '" + password + "'";
        ResultSet result = Query.getData(query);
        try {
            if (result.next()) {
                return true;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLupaPassword;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JLabel txtPassword;
    private javax.swing.JTextField txtSetEmail;
    private javax.swing.JPasswordField txtSetPassword;
    // End of variables declaration//GEN-END:variables
}
