/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hms.form;

import com.hms.model.Users;
import com.hms.query.Query;

import javax.swing.*;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 * @author Mahadi Indra <indra-182 on github.com>
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNama = new javax.swing.JLabel();
        txtEmail = new javax.swing.JLabel();
        txtPassword = new javax.swing.JLabel();
        txtSetNama = new javax.swing.JTextField();
        txtSetEmail = new javax.swing.JTextField();
        txtSetPassword = new javax.swing.JPasswordField();
        txtQuestion = new javax.swing.JLabel();
        txtSetQuestion = new javax.swing.JComboBox<>();
        txtAnswer = new javax.swing.JLabel();
        txtSetAnswer = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        btnLupaPassword = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hms/images/close.jpg"))); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1860, 10, 50, 50));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Register");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 120, -1, -1));

        txtNama.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        txtNama.setForeground(new java.awt.Color(255, 255, 255));
        txtNama.setText("Nama");
        getContentPane().add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, -1, -1));

        txtEmail.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setText("Email");
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        txtPassword.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setText("Password");
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, -1, -1));

        txtSetNama.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        txtSetNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSetNamaActionPerformed(evt);
            }
        });
        getContentPane().add(txtSetNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 240, 370, -1));

        txtSetEmail.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        getContentPane().add(txtSetEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 330, 370, -1));

        txtSetPassword.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        getContentPane().add(txtSetPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 410, 370, -1));

        txtQuestion.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        txtQuestion.setForeground(new java.awt.Color(255, 255, 255));
        txtQuestion.setText("Pertanyaan Keamanan");
        getContentPane().add(txtQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 510, -1, -1));

        txtSetQuestion.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        txtSetQuestion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Pertanyaan", "Apa buah favoritku?", "Dimana aku lahir?", "Angka favoritku?" }));
        getContentPane().add(txtSetQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 510, 370, -1));

        txtAnswer.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        txtAnswer.setForeground(new java.awt.Color(255, 255, 255));
        txtAnswer.setText("Jawaban");
        getContentPane().add(txtAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 590, -1, -1));

        txtSetAnswer.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        txtSetAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSetAnswerActionPerformed(evt);
            }
        });
        getContentPane().add(txtSetAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 590, 370, -1));

        btnRegister.setBackground(new java.awt.Color(0, 102, 204));
        btnRegister.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 680, 130, 40));

        btnLupaPassword.setBackground(new java.awt.Color(0, 102, 204));
        btnLupaPassword.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btnLupaPassword.setForeground(new java.awt.Color(255, 255, 255));
        btnLupaPassword.setText("Lupa Password");
        btnLupaPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLupaPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(btnLupaPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 680, -1, -1));

        btnLogin.setBackground(new java.awt.Color(0, 102, 204));
        btnLogin.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 740, 210, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Punya Akun?");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 750, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hms/images/outsidebg.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, -10, 2130, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:

        int choose = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin keluar?", "Exit", JOptionPane.YES_NO_OPTION);
        if (choose == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnCloseActionPerformed

    private void txtSetAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSetAnswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSetAnswerActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        if (!validateFields()) {
            return;
        }
        Users users = new Users();
        users.setName(txtSetNama.getText());
        users.setEmail(txtSetEmail.getText());
        users.setPassword(String.valueOf(txtSetPassword.getPassword()));
        users.setSecurityQuestion(txtSetQuestion.getSelectedItem().toString());
        users.setAnswer(txtSetAnswer.getText());

        if (users.getEmail().equals("superadmin@mailinator.com")) {
            users.setRole("Super Admin");
            users.setStatus("Active");
        } else {
            users.setRole("Admin");
            users.setStatus("Pending");
        }

        if (validateEmail(users.getEmail())) {
            JOptionPane.showMessageDialog(null, "Email Sudah Terdaftar");
        } else {
            String queryRegister = "INSERT INTO users(email,name, password, security_question, answer, status, role) VALUES ('" + users.getEmail() + "', '" + users.getName() + "', '" + users.getPassword() + "', '" + users.getSecurityQuestion() + "', '" + users.getAnswer() + "', '" + users.getStatus() + "', '" + users.getRole() + "')";
            Query.setData(queryRegister, "Register Berhasil");
            setVisible(false);
            new Register().setVisible(true);
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnLupaPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLupaPasswordActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new ForgotPassword().setVisible(true);
    }//GEN-LAST:event_btnLupaPasswordActionPerformed

    private void txtSetNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSetNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSetNamaActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_btnLoginActionPerformed

    public static boolean validateEmail(String email) {
        String queryCheckEmail = "SELECT COUNT(*) FROM users WHERE email = '" + email + "'";
        try {
            ResultSet resultSet = Query.getData(queryCheckEmail);
            if (resultSet.next()) {
                int count = resultSet.getInt(1);
                return count > 0;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return false;
    }


    private boolean validateFields() {
        String name = txtSetNama.getText();
        String email = txtSetEmail.getText();
        String password = String.valueOf(txtSetPassword.getPassword());
        String securityQuestions = txtSetQuestion.getSelectedItem().toString();
        String answer = txtSetAnswer.getText();

        if (securityQuestions.equals("Pilih Pilihan")) {
            JOptionPane.showMessageDialog(null, "Silakan Pilih Pilihan Pertanyaan Keamanan Terlebih Dahulu");
            return false;
        }

        if (name.isEmpty() || email.isEmpty() || password.isEmpty() || securityQuestions.isEmpty() || answer.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Field Tidak Boleh Kosong");
            return false;
        }
        return true;
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLupaPassword;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel txtAnswer;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JLabel txtNama;
    private javax.swing.JLabel txtPassword;
    private javax.swing.JLabel txtQuestion;
    private javax.swing.JTextField txtSetAnswer;
    private javax.swing.JTextField txtSetEmail;
    private javax.swing.JTextField txtSetNama;
    private javax.swing.JPasswordField txtSetPassword;
    private javax.swing.JComboBox<String> txtSetQuestion;
    // End of variables declaration//GEN-END:variables
}
